# -*- coding: utf-8 -*-
import io

path = r"c:\Users\PC\Desktop\SCSLAI\FRONT\FORMS\authorityLc\form.js"

content = (
    "/* SCSLAI \u2014 LC Authority to Deduct Form (FORM NO. 0427)\n"
    "   Single page 2550x4200. Image identical to SC copy; same coordinates.\n"
    "   Includes civil-status checkboxes (Single/Married/Widow). */\n"
    "(function(){\n"
    "\"use strict\";\n"
    "\n"
    "SCSLAI.register({\n"
    "key:\"authorityLc\",\n"
    "title:\"LC Authority to Deduct Form\",\n"
    "fieldLabels:{\n"
    "fullName:\"Full Name\",employedAs:\"Employed As\",\n"
    "officeOf:\"Office Of\",signDay:\"Day Signed\",signMonth:\"Month Signed\",\n"
    "signYear:\"Year Signed\",signPlace:\"Place Signed\",\n"
    "email:\"Email\",mobileNumber:\"Mobile Number\",permanentAddr:\"Permanent Address\"\n"
    "},\n"
    "width:2550, height:4200,\n"
    "hasPage2:false, hasCheckboxes:true, useUppercase:true,\n"
    "mobileField:\"mobileNumber\",\n"
    "pdfPrefix:\"LC-Authority-To-Deduct-\",\n"
    "pdfSuffix:\"Form\",\n"
    "images:[\"FORMS/AUTHORITY TO DEDUCT - form - LC.png\"],\n"
    "\n"
    "labels:{\n"
    "cbSingle:\"Single\",\n"
    "cbMarried:\"Married\",\n"
    "cbWidow:\"Widow\"\n"
    "},\n"
    "\n"
    "checkboxes:{\n"
    "cbSingle:{cx:1606,cy:1295,w:38,h:38,category:\"civilStatus\"},\n"
    "cbMarried:{cx:1819,cy:1295,w:38,h:38,category:\"civilStatus\"},\n"
    "cbWidow:{cx:2064,cy:1295,w:38,h:38,category:\"civilStatus\"}\n"
    "},\n"
    "\n"
    "fields:{\n"
    "/* OPENING PARAGRAPH \u2014 I, ___ ... employed as ___ ... Office of ___ */\n"
    "fullName:{x:292,y:1271,w:904,h:50,fs:24},\n"
    "employedAs:{x:842,y:1348,w:754,h:50,fs:24},\n"
    "officeOf:{x:454,y:1420,w:1025,h:50,fs:24},\n"
    "\n"
    "/* SIGNED THIS ___ DAY OF ___, 20___ AT ___ */\n"
    "signDay:{x:519,y:2280,w:151,h:50,fs:22},\n"
    "signMonth:{x:847,y:2280,w:151,h:50,fs:22},\n"
    "signYear:{x:1091,y:2280,w:91,h:50,fs:22},\n"
    "signPlace:{x:1254,y:2280,w:151,h:50,fs:22},\n"
    "\n"
    "/* CONTACT DETAILS */\n"
    "email:{x:404,y:2730,w:664,h:50,fs:22},\n"
    "mobileNumber:{x:636,y:2793,w:514,h:50,fs:22},\n"
    "permanentAddr:{x:886,y:2855,w:634,h:50,fs:22}\n"
    "},\n"
    "\n"
    "validate:function(vals,miss){\n"
    "if(!vals.fullName)miss.push(\"Full Name (I, ___)\");\n"
    "if(!vals.employedAs)miss.push(\"Presently employed as\");\n"
    "if(!vals.officeOf)miss.push(\"Office of\");\n"
    "if(!vals.signDay)miss.push(\"Day signed\");\n"
    "if(!vals.signMonth)miss.push(\"Month signed\");\n"
    "if(!vals.signYear)miss.push(\"Year signed\");\n"
    "if(!vals.mobileNumber)miss.push(\"Mobile Number\");\n"
    "},\n"
    "\n"
    "getResult:function(vals,checkedOf){\n"
    "var cs=(checkedOf&&checkedOf(\"civilStatus\"))||[];\n"
    "return{form:\"authorityLc\",fields:vals,civilStatus:cs.length?cs[0].label:\"\"};\n"
    "}\n"
    "\n"
    "});\n"
    "\n"
    "})();\n"
)

with io.open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print("written", len(content), "chars")